### ISSUE TITLE
EBADF in testComm

### ISSUE THREAD

**Issue by pwaller** [acln0/perf#24]
While looking into #23, I spied the skipped testComm test, and suspected it might be related to some of the issues I've been seeing.

I noticed that there were some ignored errors:

https://github.com/acln0/perf/blob/6861f4b5b828ac9ec30ec0eddc8d4fef199a3299/record_test.go#L1234

https://github.com/acln0/perf/blob/6861f4b5b828ac9ec30ec0eddc8d4fef199a3299/record_test.go#L1240

If I remove the skip and run `go test -count=100 -run TestReadRecord/Comm`, then every ~100 tests or so I see EBADF returning from those, and sometimes I see hangs while one side or the other is waiting for an eventfd which will never get messaged.

The skip:

https://github.com/acln0/perf/blob/6861f4b5b828ac9ec30ec0eddc8d4fef199a3299/record_test.go#L548

**Comment by pwaller** [comment]
Also worth noting that sometimes perf.Open is also returning EBADF from unix.SetNonBlock:

https://github.com/acln0/perf/blob/6861f4b5b828ac9ec30ec0eddc8d4fef199a3299/perf.go#L146

I don't yet know why but I take this as a hint that the file descriptors are getting screwed up somehow.

One theory I've been entertaining is that somewhere could be setting the file descriptors CLOEXEC or otherwise closing the filedescriptors in a racy way. I haven't yet been able to spot it in strace output.

**Comment by pwaller** [comment]
A further lead. Seen in a partial trace:

```
29549 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129129 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129139 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129129 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129139 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129549 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129129 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129549 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129127 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129127 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=129127, si_uid=1000} ---
129129 close(8)                         = -1 EBADF (Bad file descriptor)
129129 close(7)                         = -1 EBADF (Bad file descriptor)
129129 close(3)                         = 0
129129 close(8)                         = -1 EBADF (Bad file descriptor)
129129 close(7)                         = 0
129129 close(3)                         = 0
129129 close(8)                         = -1 EBADF (Bad file descriptor)
129129 close(7)                         = 0
129129 close(3)                         = 0
129129 close(8)                         = -1 EBADF (Bad file descriptor)
129129 close(7)                         = -1 EBADF (Bad file descriptor)
129129 close(3)                         = 0
129129 close(8)                         = -1 EBADF (Bad file descriptor)
129129 close(7)                         = 0
129129 close(3)                         = -1 EBADF (Bad file descriptor)
129129 close(8)                         = -1 EBADF (Bad file descriptor)
129129 close(7)                         = -1 EBADF (Bad file descriptor)
129129 close(3)                         = -1 EBADF (Bad file descriptor)
129129 close(8)                         = -1 EBADF (Bad file descriptor)
129129 close(7)                         = -1 EBADF (Bad file descriptor)
129129 close(3)                         = -1 EBADF (Bad file descriptor)
129129 close(8)                         = -1 EBADF (Bad file descriptor)
```

These are the first EBADFs seen out of hundreds of successful iterations. SIGURG is used for go's runtime to preempt. Now my working theory is that things are becoming broken after GC, which could explain why it's an intermittent/difficult to reproduce failure.

https://github.com/golang/go/blob/ef3571bf076f4255579bedb3409bdccc91555b86/src/runtime/signal_unix.go#L64-L71

**Comment by pwaller** [comment]
GOGC=off, and the bug doesn't repro, so now I'm convinced this is a "warm" line of thinking

BTW, I'm on gophers Slack if you want to sync on this some time, just PM me.

**Comment by acln0** [comment]
That is very interesting. Thank you for your fantastic work. Sadly, I've been away from this project for a while due to limited bandwidth, but the timing couldn't be better: it was already getting very close to the top of my stack. I haven't been on gophers Slack in a few months, but I'll log on these next few days at some point so we can sync up. Thanks again!

Of course, I will also look into these as soon as I get the chance.

**Comment by pwaller** [comment]
Right, think I've found the problem.

We call os.NewFile on the file descriptors:

https://github.com/acln0/perf/blob/6861f4b5b828ac9ec30ec0eddc8d4fef199a3299/record_test.go#L267

but we also close them:

https://github.com/acln0/perf/blob/6861f4b5b828ac9ec30ec0eddc8d4fef199a3299/record_test.go#L256

os.NewFile sets up a finalizer which calls close if the fd isn't closed via the newfile. So we're currently using newfile incorrectly.

https://github.com/golang/go/blob/000636fdb58c9444b17e54977382dc1d6357e8c3/src/os/file_unix.go#L170

**Comment by pwaller** [comment]
With #25 and #26 applied, the skipped test now passes reliably for me.
