### ISSUE TITLE
The way forward for the perf package

### ISSUE THREAD

**Issue by ti-mo** [acln0/perf#30]
Hi all,

I've reached out to @acln0 privately to ask about the future of this package. Unfortunately, he won't be returning to OSS anytime soon, so we'll need to find an alternative working solution in the mean time. He agrees we should try to focus the community's efforts around a single repository, since there are currently multiple forks of this repo with different patch sets.

There's also a 'competing' implementation at https://github.com/hodgesds/perf-utils, (@hodgesds) though not sure about feature overlap.

My current goal is using this library to complement https://github.com/cilium/ebpf for easy tracepoint and kprobe support, and moving out most of the `cilium/ebpf/perf` package. (cc @lmb)

Given my (very) limited familiarity with the kernel's perf API, I don't feel positioned to take up maintainership long-term, but I can already start gathering patches from forks for inclusion. (also, my availability over the summer will be limited)

I'd also like to gather the community's thoughts around this lib in particular.
- Do we stick with this API? Is it too high or low level?
- What are the biggest pain points (barring unmerged PRs)?
- Any particular reason to push for inclusion into the stdlib?

Also, where should the package live in the mean time?
- The existing `github.com/elastic/go-perf`? (@adriansr)
- `github.com/cilium/perf` is available
- Any other active organizations that have an interest in hosting this?

@pwaller @andrewkroh @florianl @tklauser @mdlayher @pengfei-su @MarkPash @fbegyn

cc, feel free to ignore/unsub if not interested, sorry for spamming!

Thanks, take care!

**Comment by hodgesds** [comment]
My 2 cents is that `golang.org/x/sys/unix` already provides a reasonable API, which most of the libraries you mention wrap or partially use. The problem with trying to make a high level API with perf events is that there are a number of complex hardware, software, and kernel configurations that breed complexity, so the enumeration of configurations is large. Here's a subset of some of the issues; First there is need to handle sampling vs counter configuration and how each needs to be configured. There are even more edge cases as well when dealing with hardware counters; hardware counters use CPU registers and will end up being scheduled on the processor (even if using counts) when the number of exceeds available registers. Note, that available registers is also dependent on the kernel NMI watchdog configuration. Then you have the group profiler configuration that needs to be handled. Next, the library will probably be used by someone who is running in a VM, which may or may not have hardware counters exposed. 

It's ***really hard*** to build a high level API on top of a complex kernel interface, without removing functionality or providing a set of defaults that may not be useful/misused in all combinations of kernel, hardware and software. The complexity breeds complexity, which means at some point the library will need to expose some config on the `PerfEventAttr` struct. Note, this does not even cover with how to use perf within the Go runtime, as it too has many caveats. I think it more worthwhile to focus in areas such as libbpf/co-re on the bpf side of things and integrating perf events into [`runtime/pprof`](https://github.com/golang/go/issues/36821). The later is how most people would want to use perf events (within Go).

**Comment by hodgesds** [comment]
That being said, I'm not against contributing/consolidating everything into a single place, as long as it is flexible enough to accommodate different use cases. It would be nice to backport all these changes as well, which is where I think a majority of the work would be.

**Comment by ti-mo** [comment]
@hodgesds Thanks for the insights! After giving it some thought, `unix` indeed provides most of what we'd need for `cilium/ebpf`, which is quite limited. Existing users were pulling in this library mostly for `Open()` and a few constants, so I've written a few wrappers on top of `unix` instead and added it to the library.

Given the low response rate to this issue, I see there's not much interest in maintaining this library further, but it was worth a try. Closing.
