### ISSUE TITLE
Is CallingThread correctly named?

### ISSUE THREAD

**Issue by pwaller** [acln0/perf#6]
https://github.com/acln0/perf/blob/master/perf.go#L24-L25

I assume the above is correct but wanted to double check. The perf docs say:

```
       pid == 0 and cpu == -1
              This measures the calling process/thread on any CPU.
```

I note that it uses the word `process/thread` for `pid==0` and I'm not really sure what this means.

The other part to my question is, how does this interact with `runtime.LockOSThread()`? Can we ensure that `Measure(func() {...})` doesn't measure other things going on within the process?

I note that https://github.com/golang/go/issues/20458 was fixed and makes LockOSThread and UnlockOSThread safe to call in pairs, even if you don't know the outer state with which you are being called.

**Comment by acln0** [comment]
Good question. I do not know the answer at this time, but perhaps there is a reasonably easy way to find out. I imagine one could create an event for a static tracepoint (such as calls to `getpid(2)`, like some of the tests use), then create two goroutines, each locked to an OS thread. On one of them, enable the event, call `getpid()`, send a signal to the other goroutine, wait for it to call `getpid()` and hear back from it, then disable the event. If the name for `CallingThread` is correct, then only one event should be observed.

**Comment by pwaller** [comment]
I did your experiment with both tracepoints and hardware counters, and I conclude that it is correctly named, and that LockOSThread and UnlockOSThread do the right thing.
